const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),vm=require('vm');
const source=fs.readFileSync(require('node:path').join(__dirname,'../service-status.js'),'utf8');
function setup({health={status:'ok',services:{database:'up'}},status=200,image=true,offline=false,hidden=false,failure=false,pending=false}={}){
 const elements={};for(const id of ['frontend-status','api-status','service-status-refresh','service-status-updated'])elements[id]={dataset:{},addEventListener:(name,fn)=>elements[id][name]=fn};
 const timers=[],events={};let requests=0,images=0,resolve;
 const response={status,ok:status>=200&&status<300,json:async()=>health};
 const box={document:{hidden,getElementById:id=>elements[id],addEventListener:(name,fn)=>events[name]=fn},navigator:{onLine:!offline},window:{addEventListener:(name,fn)=>events[name]=fn},AbortController,Date,Promise,setTimeout:fn=>{timers.push(fn);return timers.length;},clearTimeout:()=>{},setInterval:fn=>events.interval=fn,Image:class{set src(value){if(!value)return;images++;assert.match(value,/^https:\/\/controlfinance\.sysbn\.com\.br\/assets\/images\/logos\/logo-icon\.png\?status=/);queueMicrotask(()=>{this.naturalWidth=image?64:0;image?this.onload?.():this.onerror?.();});}},fetch:(url,options)=>{requests++;assert.match(url,/^https:\/\/cfapi\.sysbn\.com\.br\/health\?check=/);assert.equal(options.credentials,'omit');assert.equal(options.cache,'no-store');if(failure)return Promise.reject(new Error('offline'));if(pending)return new Promise(r=>resolve=r);return Promise.resolve(response);}};
 vm.runInNewContext(source,box);return {elements,events,timers,requests:()=>requests,images:()=>images,resolve:()=>resolve(response)};
}
const settle=()=>new Promise(resolve=>setImmediate(resolve));
test('frontend and API/database become available after independent real probe results',async()=>{const s=setup();await settle();assert.equal(s.elements['frontend-status'].dataset.state,'up');assert.equal(s.elements['api-status'].dataset.state,'up');assert.equal(s.elements['service-status-refresh'].disabled,false);assert.match(s.elements['service-status-updated'].textContent,/Última verificação/);});
test('database outage leaves frontend available',async()=>{const s=setup({status:503,health:{status:'error',services:{database:'down'}}});await settle();assert.equal(s.elements['frontend-status'].dataset.state,'up');assert.equal(s.elements['api-status'].dataset.state,'down');});
test('network or blocked requests are inconclusive rather than claiming a confirmed outage',async()=>{const s=setup({failure:true,image:false});await settle();assert.equal(s.elements['frontend-status'].dataset.state,'unknown');assert.equal(s.elements['api-status'].dataset.state,'unknown');});
test('offline clients do not make network probes',async()=>{const s=setup({offline:true});await settle();assert.equal(s.requests(),0);assert.equal(s.images(),0);assert.equal(s.elements['api-status'].dataset.state,'unknown');});
test('hidden pages do not poll and concurrent refreshes do not overlap',async()=>{const h=setup({hidden:true});h.events.interval();assert.equal(h.requests(),0);const s=setup({pending:true});s.elements['service-status-refresh'].click();s.events.interval();assert.equal(s.requests(),1);s.resolve();await settle();assert.equal(s.elements['service-status-refresh'].disabled,false);});
test('malformed successful health response is inconclusive',async()=>{const s=setup({health:{version:'1.0.0'}});await settle();assert.equal(s.elements['api-status'].dataset.state,'unknown');});
